export class CartProduct {
    id: number = 0;
    name: string = "";
    image: string = "";
    company: string = "";
    categories: string = "";
    preSelectedCategories: string = "";
    description: string = "";
    buyingPricePerUnit: number = 0;
    sellingPricePerUnit: number = 0;
    discountPrice: number = 0;
    discountTitle: string = "";
    unit: number = 0;
    unitTitle: string = "";
    quantity: number = 0;
    deliveryCharge: number = 0;
    maximumOrderQuantity: number = 0;
    orderQuantity: number = 0;
}
